#!/usr/bin/env python3
"""Refresh the final reader-facing 09_report README artifact index."""

from __future__ import annotations

import argparse
from pathlib import Path

from scripts.commands.reports.report_snapshot import build_report_snapshot, latest_result_entries
from scripts.harness.state import HarnessError, now_iso, project_root

START_MARKER = "<!-- RESEARCH_AGENT_REPORT_INDEX:START -->"
END_MARKER = "<!-- RESEARCH_AGENT_REPORT_INDEX:END -->"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Refresh 09_report/README.md with a final artifact index.")
    sub = parser.add_subparsers(dest="action", required=True)

    refresh = sub.add_parser("refresh", help="Insert or update the generated 09_report README artifact index.")
    refresh.add_argument("--project", required=True)
    refresh.add_argument("--dry-run", action="store_true", help="Print the generated block without writing README.md.")
    refresh.add_argument("--max-results", type=int, default=8)
    refresh.add_argument("--max-actions", type=int, default=5)

    return parser.parse_args()


def rel(root: Path, path: Path) -> str:
    return path.relative_to(root).as_posix()


def report_link(project_relative_path: str) -> str:
    if project_relative_path.startswith("09_report/"):
        target = project_relative_path.removeprefix("09_report/")
    else:
        target = project_relative_path
    label = project_relative_path.removeprefix("09_report/")
    return f"[{label}]({target})"


def build_block(root: Path, *, max_results: int, max_actions: int) -> str:
    report_snapshot = build_report_snapshot(root, max_files=max_results)
    lines = [
        START_MARKER,
        "",
        "## Final Artifact Index",
        "",
        f"Generated by `scripts.commands.reports.report_index` at `{now_iso()}`.",
        "",
        "This generated block lists stable reader-facing and release-facing artifacts.",
        "Working state belongs in `HANDOFF.md`, `state/`, `03_experiments/`,",
        "`04_code/`, `05_results/`, `06_writing/`, `07_reviews/`, or",
        "`08_baselines/` until it is ready for final export.",
        "",
    ]

    lines.extend(["", "## Report And Release Entry Points", ""])
    stable_entries = [
        "09_report/paper/main.tex",
        "09_report/src/",
        "09_report/analysis/",
        "09_report/figures/",
    ]
    for entry in stable_entries:
        path = root / entry
        if path.exists():
            lines.append(f"- {report_link(entry)}")

    table_lines: list[str] = []
    for table in report_snapshot["tables"]:
        table_lines.append(f"- {report_link(str(table['path']))}: {table['rows']} data row(s).")
    if table_lines:
        lines.extend(["", "## Report Tables", "", *table_lines])

    results = latest_result_entries(root, max_results)
    if results:
        lines.extend(["", "## Latest Result Files", ""])
        for path in results:
            marker = "/" if path.is_dir() else ""
            lines.append(f"- {report_link(rel(root, path))}{marker}")

    lines.extend(["", END_MARKER, ""])
    return "\n".join(lines)


def insert_block(existing: str, block: str, root: Path) -> str:
    if START_MARKER in existing and END_MARKER in existing:
        before, _, remainder = existing.partition(START_MARKER)
        _, _, after = remainder.partition(END_MARKER)
        suffix = after.lstrip()
        if suffix:
            return before.rstrip() + "\n\n" + block.rstrip() + "\n\n" + suffix
        return before.rstrip() + "\n\n" + block.rstrip() + "\n"
    if existing.strip():
        lines = existing.splitlines()
        if lines and lines[0].startswith("# "):
            return "\n".join([lines[0], "", block.rstrip(), "", *lines[1:]]).rstrip() + "\n"
        return block.rstrip() + "\n\n" + existing.lstrip()
    title = "{{PROJECT_NAME}}" if root.name == "template" else root.name.replace("_", " ").replace("-", " ").title()
    return f"# {title}\n\n{block.rstrip()}\n"


def refresh_project_index(root: Path, *, max_results: int = 8, max_actions: int = 5) -> tuple[Path, bool]:
    report = root / "09_report"
    if not report.is_dir():
        raise HarnessError(f"Missing report directory: {report}")
    block = build_block(root, max_results=max_results, max_actions=max_actions)
    readme = report / "README.md"
    existing = readme.read_text(encoding="utf-8") if readme.is_file() else ""
    updated = insert_block(existing, block, root)
    if updated != existing:
        readme.write_text(updated, encoding="utf-8")
        return readme, True
    return readme, False


def refresh(args: argparse.Namespace) -> int:
    root = project_root(args.project)
    if args.dry_run:
        report = root / "09_report"
        if not report.is_dir():
            raise HarnessError(f"Missing report directory: {report}")
        print(build_block(root, max_results=args.max_results, max_actions=args.max_actions))
        return 0
    readme, changed = refresh_project_index(root, max_results=args.max_results, max_actions=args.max_actions)
    if changed:
        print(f"updated: {readme.relative_to(root)}")
    else:
        print(f"up to date: {readme.relative_to(root)}")
    return 0


def main() -> int:
    args = parse_args()
    try:
        if args.action == "refresh":
            return refresh(args)
        raise HarnessError(f"Unknown action: {args.action}")
    except HarnessError as exc:
        print(f"error: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
